version: '3'
services:
  web:
    build:
      context: ../
      dockerfile: Dockerfile.demo
      args:
        - HEIMDALL_DB_HOST=db
        - HEIMDALL_DB_USERNAME=postgres
        - HEIMDALL_DB_PASSWORD=postgres
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      TERM: "xterm-256color"

  db:
    image: postgis/postgis:13-3.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ../tmp/demo_postgresql:/var/lib/postgresql/data
